import type { LucideIcon } from "lucide-react";
import {
  Award,
  Blocks,
  Bot,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building,
  Bus,
  Calculator,
  CalendarX,
  ChartLine,
  Check,
  Clock,
  CreditCard,
  Factory,
  FileCheck,
  FileLock2,
  Files,
  FlaskConical,
  Gauge,
  Gem,
  GraduationCap,
  Handshake,
  HeartHandshake,
  House,
  Languages,
  Layers,
  LayoutDashboard,
  Lock,
  Map as MapIcon,
  Maximize2,
  MessagesSquare,
  MonitorPlay,
  MousePointer2,
  PackageCheck,
  Plane,
  PlaneTakeoff,
  Pointer,
  Puzzle,
  Radar,
  Receipt,
  Rocket,
  Route,
  SatelliteDish,
  ScanFace,
  ScanSearch,
  Search,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkle,
  Sparkles,
  Target,
  Timer,
  TrendingUp,
  Truck,
  UserCheck,
  Users,
  Utensils,
  Wallet,
  Warehouse,
  Workflow,
  Zap,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  award: Award,
  blocks: Blocks,
  bot: Bot,
  boxes: Boxes,
  "brain-circuit": BrainCircuit,
  briefcase: Briefcase,
  building: Building,
  bus: Bus,
  calculator: Calculator,
  "calendar-x": CalendarX,
  "chart-line": ChartLine,
  check: Check,
  clock: Clock,
  "credit-card": CreditCard,
  factory: Factory,
  "file-check": FileCheck,
  "file-lock-2": FileLock2,
  files: Files,
  "flask-conical": FlaskConical,
  gauge: Gauge,
  gem: Gem,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  "heart-handshake": HeartHandshake,
  house: House,
  languages: Languages,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  lock: Lock,
  map: MapIcon,
  "maximize-2": Maximize2,
  "messages-square": MessagesSquare,
  "monitor-play": MonitorPlay,
  "mouse-pointer-2": MousePointer2,
  "package-check": PackageCheck,
  plane: Plane,
  "plane-takeoff": PlaneTakeoff,
  pointer: Pointer,
  puzzle: Puzzle,
  radar: Radar,
  receipt: Receipt,
  rocket: Rocket,
  route: Route,
  "satellite-dish": SatelliteDish,
  "scan-face": ScanFace,
  "scan-search": ScanSearch,
  search: Search,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sparkle: Sparkle,
  sparkles: Sparkles,
  target: Target,
  timer: Timer,
  "trending-up": TrendingUp,
  truck: Truck,
  "user-check": UserCheck,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  warehouse: Warehouse,
  workflow: Workflow,
  zap: Zap,
};

export function IndustryIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICON_MAP[name] ?? Sparkles;
  return <Icon className={className} aria-hidden />;
}
